project:
  type: website
  output-dir: docs

website:
  title: "MLOps with vetiver"
  description: "Version, share, deploy, and monitor your R and Python models"
  open-graph: true
  twitter-card: true
  site-url: https://vetiver.rstudio.com
  repo-url: https://github.com/tidymodels/vetiver.rstudio.com
  repo-actions: [edit, issue]
  page-navigation: true
  reader-mode: true
  favicon: "images/favicon.ico"
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){width=65px}](https://www.rstudio.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tidymodels/vetiver-r
      - icon: github
        href: https://github.com/tidymodels/vetiver-python

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: https://tidymodels.github.io/vetiver-python
        text: Python Function Reference
      - href: https://vetiver.tidymodels.org/
        text: R Function Reference


format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

